<a href="https://colab.research.google.com/github/AravaChoudhary/ML-Pipeline-/blob/main/KNN_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,n_features=3,n_redundant=0,n_classes=2,random_state=1)

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [4]:
#Model Training
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()

In [5]:
clf.fit(X_train,y_train)

KNeighborsClassifier()

In [8]:
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Confusion Matrix : \n",confusion_matrix(y_test,y_pred))
print("\nAccuracy Score : ",accuracy_score(y_test,y_pred))
print("\nClassification Report : \n\n",classification_report(y_test,y_pred))

Confusion Matrix : 
 [[122  23]
 [ 21 134]]

Accuracy Score :  0.8533333333333334

Classification Report : 

               precision    recall  f1-score   support

           0       0.85      0.84      0.85       145
           1       0.85      0.86      0.86       155

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [10]:
# Hyperparameter Tuning
from sklearn.model_selection import GridSearchCV

params = {
    'n_neighbors' : [3,5,6,7,9,11,13],
    'weights' : ['uniform','distance'],
    'algorithm' : ['auto','ball_tree','kd_tree','brute'],
    'leaf_size' : [20,30,40,50]
}

grid = GridSearchCV(estimator = clf,param_grid=params,cv=5,verbose=3)
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [11]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.871 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.850 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.793 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.857 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.836 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.807 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [12]:
grid.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 11, 'weights': 'uniform'}

In [13]:
grid.best_score_

0.8514285714285714

In [21]:
tune = grid.best_estimator_
y_pred_tune = tune.predict(X_test)
print("Confusion Matrix : \n",confusion_matrix(y_test,y_pred_tune))
print("\nAccuracy Score : ",accuracy_score(y_test,y_pred_tune))
print("\nClassification Report : \n\n",classification_report(y_test,y_pred_tune))

Confusion Matrix : 
 [[124  21]
 [ 19 136]]

Accuracy Score :  0.8666666666666667

Classification Report : 

               precision    recall  f1-score   support

           0       0.87      0.86      0.86       145
           1       0.87      0.88      0.87       155

    accuracy                           0.87       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.87      0.87      0.87       300

